#!/usr/bin/env julia
#
# Build `jl-pkg/GrammarOfGraphics/Artifacts.toml` from the per-platform engines
# the release matrix has already compiled.
#
# **Why this exists at all.** Julia is the one binding that did not ship an
# engine: `Pkg.add` gave a package that loaded and then refused on the first
# plot, and the README told the reader to install Rust. Every other binding
# solves this its own way — R's `configure` bundles the binary, Python ships a
# platform wheel, JavaScript resolves a per-platform optional dependency — and
# `Artifacts.toml` is Julia's answer, so a reader gets the engine from
# `Pkg.add` like everyone else.
#
# **Two things here are not guesses and cost a Linux user everything if wrong.**
#
# ① An entry with **no** `libc` tag matches glibc and **not** musl. Julia
#   defaults the missing tag rather than treating it as a wildcard, measured
#   rather than assumed. Our Linux engines are statically linked against musl
#   and so run on both, which is the whole reason that target was chosen — so
#   each Linux arch gets **two entries pointing at one tarball**, and a musl
#   reader is not silently handed nothing.
#
# ② The `git-tree-sha1` is the hash of the *unpacked tree*, not of the tarball,
#   so it cannot be written by hand. `create_artifact` computes it and
#   `archive_artifact` returns the tarball's own sha256; both are read back out
#   of Julia rather than typed.
#
# Usage, from the repository root, after the matrix has left one binary per
# target in `dist/<target>/gog-cli[.exe]`:
#
#     julia .github/make-julia-artifacts.jl <tag> [dist-dir]
#
# `<tag>` is the GitHub release the tarballs are uploaded to; the URLs point
# there. It writes the tarballs beside the binaries for the workflow to upload,
# and prints what it wrote.

using Pkg.Artifacts, TOML

const ARTIFACT = "gog_cli"

# Each release target, and the Julia platforms it serves. A Linux row lists two
# because one static binary answers for both libcs (see ① above).
const TARGETS = [
    ("darwin-arm64", [(arch = "aarch64", os = "macos",   libc = nothing)]),
    ("darwin-x64",   [(arch = "x86_64",  os = "macos",   libc = nothing)]),
    ("linux-x64",    [(arch = "x86_64",  os = "linux",   libc = "glibc"),
                      (arch = "x86_64",  os = "linux",   libc = "musl")]),
    ("linux-arm64",  [(arch = "aarch64", os = "linux",   libc = "glibc"),
                      (arch = "aarch64", os = "linux",   libc = "musl")]),
    ("win32-x64",    [(arch = "x86_64",  os = "windows", libc = nothing)]),
]

function main(tag::AbstractString, dist::AbstractString)
    base = "https://github.com/psychometrician/gog/releases/download/$tag"
    entries = String[]
    wrote = 0

    for (target, platforms) in TARGETS
        exe = occursin("win32", target) ? "gog-cli.exe" : "gog-cli"
        src = joinpath(dist, target, exe)
        if !isfile(src)
            @warn "no engine for $target, skipping" path=src
            continue
        end

        # The artifact is a directory holding one executable, which is what
        # `bundled_cli()` looks into.
        hash = create_artifact() do dir
            cp(src, joinpath(dir, exe))
            Sys.iswindows() || chmod(joinpath(dir, exe), 0o755)
        end
        tarball = joinpath(dist, "gog-cli-$target.tar.gz")
        sha = archive_artifact(hash, tarball)
        tree = bytes2hex(hash.bytes)
        wrote += 1
        println("  $target  tree $tree  sha256 $(sha[1:16])…  $(filesize(tarball)) bytes")

        for p in platforms
            io = IOBuffer()
            println(io, "[[$ARTIFACT]]")
            println(io, "arch = \"$(p.arch)\"")
            println(io, "os = \"$(p.os)\"")
            p.libc === nothing || println(io, "libc = \"$(p.libc)\"")
            println(io, "git-tree-sha1 = \"$tree\"")
            # Not lazy: the engine is the package's whole purpose, and a reader
            # who has to ask for it separately is back where they started.
            println(io, "lazy = false")
            println(io)
            println(io, "    [[$ARTIFACT.download]]")
            println(io, "    url = \"$base/gog-cli-$target.tar.gz\"")
            println(io, "    sha256 = \"$sha\"")
            push!(entries, String(take!(io)))
        end
    end

    wrote == 0 && error("no engines found under $dist — nothing to bind")

    out = joinpath("jl-pkg", "GrammarOfGraphics", "Artifacts.toml")
    open(out, "w") do io
        println(io, "# Generated by .github/make-julia-artifacts.jl — do not edit by hand.")
        println(io, "# The engine, one entry per platform Julia can tell apart. A Linux arch")
        println(io, "# appears twice because one statically linked binary answers for both")
        println(io, "# libcs, and an entry that names neither would reach glibc alone.")
        println(io)
        print(io, join(entries, "\n"))
    end
    println("wrote $out — $(length(entries)) entries over $wrote tarballs")
end

if abspath(PROGRAM_FILE) == @__FILE__
    length(ARGS) >= 1 || error("usage: julia .github/make-julia-artifacts.jl <tag> [dist-dir]")
    main(ARGS[1], length(ARGS) >= 2 ? ARGS[2] : "dist")
end
